name: Build and Push to ECR

on:
  push:
    branches:
      - main

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        run: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 373317459706.dkr.ecr.us-east-1.amazonaws.com

      - name: Build, tag, and push image to Amazon ECR
        run: |
          docker build -t dorismedplus:${{github.run_number}} .
          docker tag dorismedplus:${{github.run_number}} 373317459706.dkr.ecr.us-east-1.amazonaws.com/dorismedplus:${{github.run_number}}
          docker push 373317459706.dkr.ecr.us-east-1.amazonaws.com/dorismedplus:${{github.run_number}}

